#pragma once
#include <cstdlib>
#include "player_fish_image.h"
#include "interface_design_tool.h"

void main_interface_write();
void main_interface_image(int color1, int color2, int color3, int color4, int color5);

void main_interface_write() {
	system("cls");
	int color1 = 12;
	int color2 = 14;
	int color3 = 13;
	int color4 = 11;
	int color5 = 11;
	main_interface_image(color1, color2, color3, color4, color5);
	gotoxy(71, 30);
	color_change(14);		//150 45  중간 75 22
	printf("게임  시작\n");
	color_change(7);
	gotoxy(65, 35);
	printf("Enter키를   누르시오.\n");
}
void main_interface_image(int color1, int color2, int color3, int color4, int color5) {
	color_change(color1);  //4: 빨간색 6: 노란색 0: 검은색 12: 연한 빨간색
	int x = 0, y = 0;
	y += 5;
	gotoxy(x, y);
	printf("■");
	gotoxy(x, y - 1);
	printf("■");
	gotoxy(x, y + 1);
	printf("■");
	gotoxy(x + 2, y + 2);
	printf("■");
	gotoxy(x + 2, y - 2);
	printf("■");
	gotoxy(x + 4, y - 2);
	printf("■");
	gotoxy(x + 4, y + 3);
	printf("■");
	gotoxy(x + 6, y + 3);
	printf("■");
	gotoxy(x + 8, y + 4);
	printf("■");
	gotoxy(x + 10, y + 4);
	printf("■");
	gotoxy(x + 12, y + 4);
	printf("■");
	gotoxy(x + 14, y + 5);
	printf("■");
	gotoxy(x + 16, y + 5);
	printf("■");
	gotoxy(x + 18, y + 5);
	printf("■");
	gotoxy(x + 20, y + 5);
	printf("■");
	gotoxy(x + 22, y + 5);
	printf("■");
	gotoxy(x + 24, y + 5);
	printf("■");
	gotoxy(x + 26, y + 5);
	printf("■");
	gotoxy(x + 28, y + 5);
	printf("■");
	gotoxy(x + 30, y + 5);
	printf("■");
	gotoxy(x + 32, y + 5);
	printf("■");
	gotoxy(x + 18, y - 2);
	printf("■");
	gotoxy(x + 18, y - 1);
	printf("■");
	gotoxy(x + 18, y);
	printf("■");
	gotoxy(x + 18, y + 1);
	printf("■");
	gotoxy(x + 18, y + 2);
	printf("■");
	gotoxy(x + 18, y + 3);
	printf("■");
	gotoxy(x + 6, y - 3);
	printf("■");
	gotoxy(x + 8, y - 3);
	printf("■");
	gotoxy(x + 16, y - 3);
	printf("■");
	gotoxy(x + 16, y + 4);
	printf("■");
	gotoxy(x + 10, y - 4);
	printf("■");
	gotoxy(x + 12, y - 4);
	printf("■");
	gotoxy(x + 14, y - 4);
	printf("■");
	gotoxy(x + 16, y - 4);
	printf("■");
	gotoxy(x + 18, y - 4);
	printf("■");
	gotoxy(x + 20, y - 4);
	printf("■");
	gotoxy(x + 22, y - 4);
	printf("■");
	gotoxy(x + 24, y - 4);
	printf("■");
	gotoxy(x + 26, y - 4);
	printf("■");
	gotoxy(x + 28, y - 3);
	printf("■");
	gotoxy(x + 30, y - 3);
	printf("■");
	gotoxy(x + 32, y - 3);
	printf("■");
	gotoxy(x + 34, y - 3);
	printf("■");
	gotoxy(x + 22, y - 2);
	printf("■");
	gotoxy(x + 22, y - 1);
	printf("■");
	gotoxy(x + 22, y);
	printf("■");
	gotoxy(x + 22, y + 2);
	printf("■");
	gotoxy(x + 22, y + 3);
	printf("■");
	gotoxy(x + 26, y);
	printf("■");
	gotoxy(x + 26, y - 1);
	printf("■");
	gotoxy(x + 26, y + 3);
	printf("■");
	gotoxy(x + 26, y + 4);
	printf("■");
	gotoxy(x + 30, y - 1);
	printf("■");
	gotoxy(x + 30, y - 2);
	printf("■");
	gotoxy(x + 30, y + 2);
	printf("■");
	gotoxy(x + 30, y + 3);
	printf("■");
	gotoxy(x + 34, y + 1);
	printf("■");
	gotoxy(x + 34, y + 2);
	printf("■");
	gotoxy(x + 34, y);
	printf("■");
	gotoxy(x + 36, y - 2);
	printf("■");
	gotoxy(x + 38, y - 2);
	printf("■");
	gotoxy(x + 40, y - 1);
	printf("■");
	gotoxy(x + 40, y + 2);
	printf("■");
	gotoxy(x + 38, y + 3);
	printf("■");
	gotoxy(x + 36, y + 4);
	printf("■");
	gotoxy(x + 34, y + 4);
	printf("■");  // 6 8 7: 가운데 비움 
	gotoxy(x + 42, y);
	printf("■");
	gotoxy(x + 42, y + 1);
	printf("■"); //테두리

	color_change(color2);
	gotoxy(x + 2, y - 1);
	printf("■");
	gotoxy(x + 4, y - 1);
	printf("■");
	gotoxy(x + 6, y - 1);
	printf("■");
	gotoxy(x + 8, y - 1);
	printf("■");
	gotoxy(x + 12, y - 1);
	printf("■");
	gotoxy(x + 14, y - 1);
	printf("■");
	gotoxy(x + 16, y - 1);
	printf("■");
	gotoxy(x + 20, y - 1);
	printf("■");
	gotoxy(x + 24, y - 1);
	printf("■");
	gotoxy(x + 28, y - 1);
	printf("■");
	gotoxy(x + 32, y - 1);
	printf("■");
	gotoxy(x + 34, y - 1);
	printf("■");
	gotoxy(x + 36, y - 1);
	printf("■");
	gotoxy(x + 38, y - 1);
	printf("■");
	gotoxy(x + 6, y - 2);
	printf("■");
	gotoxy(x + 8, y - 2);
	printf("■");
	gotoxy(x + 10, y - 2);
	printf("■");
	gotoxy(x + 12, y - 2);
	printf("■");
	gotoxy(x + 14, y - 2);
	printf("■");
	gotoxy(x + 16, y - 2);
	printf("■");
	gotoxy(x + 20, y - 2);
	printf("■");
	gotoxy(x + 24, y - 2);
	printf("■");
	gotoxy(x + 26, y - 2);
	printf("■");
	gotoxy(x + 28, y - 2);
	printf("■");
	gotoxy(x + 32, y - 2);
	printf("■");
	gotoxy(x + 34, y - 2);
	printf("■");
	gotoxy(x + 10, y - 3);
	printf("■");
	gotoxy(x + 12, y - 3);
	printf("■");
	gotoxy(x + 14, y - 3);
	printf("■");
	gotoxy(x + 18, y - 3);
	printf("■");
	gotoxy(x + 20, y - 3);
	printf("■");
	gotoxy(x + 22, y - 3);
	printf("■");
	gotoxy(x + 24, y - 3);
	printf("■");
	gotoxy(x + 26, y - 3);
	printf("■");
	gotoxy(x + 2, y);
	printf("■");
	gotoxy(x + 4, y);
	printf("■");
	gotoxy(x + 6, y);
	printf("■");
	gotoxy(x + 8, y);
	printf("■");
	gotoxy(x + 10, y);
	printf("■");
	gotoxy(x + 12, y);
	printf("■");
	gotoxy(x + 14, y);
	printf("■");
	gotoxy(x + 16, y);
	printf("■");
	gotoxy(x + 20, y);
	printf("■");
	gotoxy(x + 24, y);
	printf("■");
	gotoxy(x + 28, y);
	printf("■");
	gotoxy(x + 30, y);
	printf("■");
	gotoxy(x + 32, y);
	printf("■");
	gotoxy(x + 36, y);
	printf("■");
	gotoxy(x + 38, y);
	printf("■");
	gotoxy(x + 40, y);
	printf("■");
	gotoxy(x + 2, y + 1);
	printf("■");
	gotoxy(x + 4, y + 1);
	printf("■");
	gotoxy(x + 6, y + 1);
	printf("■");
	gotoxy(x + 8, y + 1);
	printf("■");
	gotoxy(x + 10, y + 1);
	printf("■");
	gotoxy(x + 12, y + 1);
	printf("■");
	gotoxy(x + 14, y + 1);
	printf("■");
	gotoxy(x + 16, y + 1);
	printf("■");
	gotoxy(x + 20, y + 1);
	printf("■");
	gotoxy(x + 22, y + 1);
	printf("■");
	gotoxy(x + 24, y + 1);
	printf("■");
	gotoxy(x + 26, y + 1);
	printf("■");
	gotoxy(x + 28, y + 1);
	printf("■");
	gotoxy(x + 30, y + 1);
	printf("■");
	gotoxy(x + 32, y + 1);
	printf("■");
	gotoxy(x + 36, y + 1);
	printf("■");
	gotoxy(x + 38, y + 1);
	printf("■");
	gotoxy(x + 40, y + 1);
	printf("■");
	gotoxy(x + 4, y + 2);
	printf("■");
	gotoxy(x + 6, y + 2);
	printf("■");
	gotoxy(x + 8, y + 2);
	printf("■");
	gotoxy(x + 10, y + 2);
	printf("■");
	gotoxy(x + 12, y + 2);
	printf("■");
	gotoxy(x + 14, y + 2);
	printf("■");
	gotoxy(x + 16, y + 2);
	printf("■");
	gotoxy(x + 20, y + 2);
	printf("■");
	gotoxy(x + 24, y + 2);
	printf("■");
	gotoxy(x + 26, y + 2);
	printf("■");
	gotoxy(x + 28, y + 2);
	printf("■");
	gotoxy(x + 32, y + 2);
	printf("■");
	gotoxy(x + 36, y + 2);
	printf("■");
	gotoxy(x + 38, y + 2);
	printf("■");
	gotoxy(x + 8, y + 3);
	printf("■");
	gotoxy(x + 10, y + 3);
	printf("■");
	gotoxy(x + 12, y + 3);
	printf("■");
	gotoxy(x + 14, y + 3);
	printf("■");
	gotoxy(x + 16, y + 3);
	printf("■");
	gotoxy(x + 20, y + 3);
	printf("■");
	gotoxy(x + 24, y + 3);
	printf("■");
	gotoxy(x + 28, y + 3);
	printf("■");
	gotoxy(x + 32, y + 3);
	printf("■");
	gotoxy(x + 34, y + 3);
	printf("■");
	gotoxy(x + 36, y + 3);
	printf("■");
	gotoxy(x + 14, y + 4);
	printf("■");
	gotoxy(x + 18, y + 4);
	printf("■");
	gotoxy(x + 20, y + 4);
	printf("■");
	gotoxy(x + 22, y + 4);
	printf("■");
	gotoxy(x + 24, y + 4);
	printf("■");
	gotoxy(x + 28, y + 4);
	printf("■");
	gotoxy(x + 30, y + 4);
	printf("■");
	gotoxy(x + 32, y + 4);
	printf("■");

	color_change(color3);
	gotoxy(x + 10, y - 1);
	printf("★");
	
	color_change(color4);
	gotoxy(x + 42, y - 2);
	printf("■");
	gotoxy(x + 42, y - 1);
	printf("■");
	gotoxy(x + 42, y + 2);
	printf("■");
	gotoxy(x + 42, y + 3);
	printf("■");
	gotoxy(x + 44, y);
	printf("■");
	gotoxy(x + 44, y - 3);
	printf("■");
	gotoxy(x + 44, y - 2);
	printf("■");
	gotoxy(x + 44, y - 1);
	printf("■");
	gotoxy(x + 44, y + 1);
	printf("■");
	gotoxy(x + 44, y + 2);
	printf("■");
	gotoxy(x + 44, y + 3);
	printf("■");
	gotoxy(x + 44, y + 4);
	printf("■");
	gotoxy(x + 46, y - 3);
	printf("■");
	gotoxy(x + 46, y - 2);
	printf("■");
	gotoxy(x + 46, y - 1);
	printf("■");
	gotoxy(x + 46, y + 2);
	printf("■");
	gotoxy(x + 46, y + 3);
	printf("■");
	gotoxy(x + 46, y + 4);
	printf("■");
	gotoxy(x + 48, y - 2);
	printf("■");
	gotoxy(x + 48, y - 3);
	printf("■");
	gotoxy(x + 48, y - 4);
	printf("■");
	gotoxy(x + 50, y - 3);
	printf("■");
	gotoxy(x + 50, y - 4);
	printf("■");
	gotoxy(x + 52, y - 4);
	printf("■");
	gotoxy(x + 48, y + 3);
	printf("■");
	gotoxy(x + 48, y + 4);
	printf("■");
	gotoxy(x + 48, y + 5);
	printf("■");
	gotoxy(x + 50, y + 4);
	printf("■");
	gotoxy(x + 50, y + 5);
	printf("■");
	gotoxy(x + 52, y + 5);
	printf("■");

	color_change(color5);
	/*gotoxylimit_line(x + 12, y - 5, "▲", 8);
	gotoxylimit_line(x + 28, y - 4, "▲", 2);
	gotoxylimit_line(x + 12, y + 5, "▼", 1);
	gotoxylimit_line(x + 14, y + 6, "▲", 9);*/
}